// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5z2MaEB785J978fJXnEhnMWAMBqIF8pU',
    appId: '1:586680111067:web:614197c9e24a369f64e1fe',
    messagingSenderId: '586680111067',
    projectId: 'eki-express-74357',
    authDomain: 'eki-express-74357.firebaseapp.com',
    storageBucket: 'eki-express-74357.appspot.com',
    measurementId: 'G-SC7Z2DNYSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqqP2DD8NQnkhjkYV98VVwnE-5Nk1yes',
    appId: '1:586680111067:android:b1e52e7d1b01fbf364e1fe',
    messagingSenderId: '586680111067',
    projectId: 'eki-express-74357',
    storageBucket: 'eki-express-74357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP-J-yhfpUH0LbTvamfC2GVakI6V5wxKc',
    appId: '1:586680111067:ios:453e1ffc734db45464e1fe',
    messagingSenderId: '586680111067',
    projectId: 'eki-express-74357',
    storageBucket: 'eki-express-74357.appspot.com',
    androidClientId: '586680111067-j4np3v91vefa7vpjtsh4lsjsglkm35kl.apps.googleusercontent.com',
    iosClientId: '586680111067-8cvr2n3putm33812lu5ifvin8j8473fn.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.6amMart',
  );
}
